version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'evmos' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
      - name: address_labels
  - name: bronze 
    database: evmos
    schema: bronze 
    tables: 
      - name: sample_blocks
      - name: sample_txs
  - name: streamline 
    database: streamline
    schema: evmos_dev
    tables: 
      - name: tendermint_block
      - name: tendermint_tx_search
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
