version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'evmos' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "EVMOS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "EVMOS" }}
    tables:
      - name: blocks
      - name: transactions
